/**
 * Web Server — Interactive agent playground.
 *
 * Hosts a browser UI on a port. Streams agent execution in real-time
 * via Server-Sent Events so you can watch perceive→reason→plan→act→reflect live.
 *
 * Run:  npm start                         (port 3000)
 *       PORT=8080 npm start               (custom port)
 *       ANTHROPIC_API_KEY=sk-... npm start (pre-set key)
 */

import * as http from "http";
import * as url from "url";
import Anthropic from "@anthropic-ai/sdk";
import { AgentFactory, AgentBlueprint } from "./factory";
import { AgentHarness } from "./agent";
import { ClaudeReasoner } from "./llm";
import { ToolDefinition } from "./tools";
import { html } from "./ui";

const PORT = parseInt(process.env.PORT ?? "3000", 10);

// ── Built-in tools for demos ───────────────────────────────────

const searchTool: ToolDefinition = {
  name: "search",
  description: "Search for information on a topic",
  parameters: { query: "The search query" },
  execute: async (params) => {
    const q = params.query as string;
    return {
      results: [
        `[Source A] Key finding about "${q}": significant improvements observed.`,
        `[Source B] Study shows "${q}" adoption growing rapidly.`,
        `[Source C] Expert analysis: "${q}" is transforming the landscape.`,
      ],
    };
  },
};

const calcTool: ToolDefinition = {
  name: "calculate",
  description: "Evaluate a math expression",
  parameters: { expression: "a math expression like (7+5)*3" },
  execute: async (params) => {
    const expr = String(params.expression).replace(/[^0-9+\-*/().  ]/g, "");
    const result = Function(`"use strict"; return (${expr})`)();
    return { result: Number(result) };
  },
};

const writeTool: ToolDefinition = {
  name: "compose",
  description: "Compose a written document",
  parameters: { topic: "Topic", content: "Content to include" },
  execute: async (params) => ({
    document: `# ${params.topic}\n\n${params.content}\n\n---\nGenerated by Agent Pipeline`,
  }),
};

// ── Demos ──────────────────────────────────────────────────────

interface Demo {
  id: string;
  name: string;
  description: string;
  goal: string;
  mode: "single" | "multi";
  blueprints?: AgentBlueprint[];
  singleTools?: ToolDefinition[];
  singlePersona?: string;
  tasks?: Array<{ description: string; metadata?: Record<string, unknown> }>;
}

function buildDemos(client: Anthropic): Demo[] {
  return [
    {
      id: "math",
      name: "Math Solver",
      description: "Single agent solves a math word problem using the calculate tool",
      goal: "A store sells apples for $3 each. Alice buys 7 apples and Bob buys 5 apples. How much did they spend in total?",
      mode: "single",
      singleTools: [calcTool],
      singlePersona: "You are a math solver. Use the calculate tool to compute answers. Be precise and show your work.",
    },
    {
      id: "research",
      name: "Research Team",
      description: "3 agents collaborate: Researcher → Writer → Reviewer",
      goal: "AI-driven automation in healthcare",
      mode: "multi",
      blueprints: [
        {
          name: "Researcher",
          description: "Gathers information from sources",
          tools: [searchTool],
          reasoner: new ClaudeReasoner({ client, persona: "You are a researcher. Use the search tool to find information." }),
        },
        {
          name: "Writer",
          description: "Composes reports from research",
          tools: [writeTool],
          reasoner: new ClaudeReasoner({ client, persona: "You are a writer. Use the compose tool to create a report." }),
        },
        {
          name: "Reviewer",
          description: "Reviews for quality",
          tools: [],
          reasoner: new ClaudeReasoner({ client, persona: "You are a reviewer. Assess quality and provide feedback." }),
        },
      ],
      tasks: [
        { description: "Research the topic", metadata: { tool: "search", toolParams: { query: "AI-driven automation in healthcare" } } },
        { description: "Write a report", metadata: { tool: "compose", toolParams: { topic: "AI in Healthcare", content: "Research findings pending" } } },
        { description: "Review the report" },
      ],
    },
    {
      id: "custom",
      name: "Custom Goal",
      description: "Type your own goal — single agent with search + calculate tools",
      goal: "",
      mode: "single",
      singleTools: [searchTool, calcTool, writeTool],
      singlePersona: "You are a helpful assistant. Use the available tools to accomplish the user's goal.",
    },
  ];
}

// ── SSE helpers ────────────────────────────────────────────────

function sseHeaders(): Record<string, string> {
  return {
    "Content-Type": "text/event-stream",
    "Cache-Control": "no-cache",
    Connection: "keep-alive",
    "Access-Control-Allow-Origin": "*",
  };
}

function sendSSE(res: http.ServerResponse, event: string, data: unknown) {
  res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);
}

// ── Request body parser ────────────────────────────────────────

function parseBody(req: http.IncomingMessage): Promise<Record<string, unknown>> {
  return new Promise((resolve, reject) => {
    let body = "";
    req.on("data", (chunk) => (body += chunk));
    req.on("end", () => {
      try { resolve(JSON.parse(body)); }
      catch { reject(new Error("Invalid JSON")); }
    });
  });
}

// ── Run single agent with SSE streaming ────────────────────────

async function runSingleAgent(
  res: http.ServerResponse,
  client: Anthropic,
  goal: string,
  tools: ToolDefinition[],
  persona: string
) {
  const reasoner = new ClaudeReasoner({ client, persona });
  const agent = new AgentHarness({
    id: "web_agent",
    name: "Agent",
    description: "Interactive agent",
    reasoner,
    tools: (() => {
      const { ToolRegistry } = require("./tools");
      const reg = new ToolRegistry();
      for (const t of tools) reg.register(t);
      return reg;
    })(),
  });

  sendSSE(res, "status", { phase: "starting", agent: "Agent" });

  for await (const { node, state } of agent.stream(goal)) {
    sendSSE(res, "step", {
      node,
      agent: "Agent",
      details: getStepDetails(node, state),
    });
  }

  sendSSE(res, "status", { phase: "complete" });

  // Memory summary
  const episodes = agent.memory.episodic.all();
  if (episodes.length > 0) {
    sendSSE(res, "memory", { episodes: episodes.map((e) => ({ action: e.action, outcome: e.outcome, reward: e.reward })) });
  }

  sendSSE(res, "done", {});
  res.end();
}

// ── Run multi-agent orchestration with SSE ─────────────────────

async function runMultiAgent(
  res: http.ServerResponse,
  client: Anthropic,
  goal: string,
  demo: Demo
) {
  const factory = new AgentFactory();

  for (const bp of demo.blueprints!) {
    factory.registerBlueprint(bp);
  }

  sendSSE(res, "status", { phase: "creating_agents", count: demo.blueprints!.length });

  // Create agents and run them one by one for streaming visibility
  const agents: AgentHarness[] = [];
  for (const bp of demo.blueprints!) {
    agents.push(factory.createFromBlueprint(bp.name));
  }

  // Register tasks
  const taskPlan = demo.tasks ?? [];
  for (let i = 0; i < taskPlan.length; i++) {
    const assignee = i < agents.length ? agents[i].id : undefined;
    factory.tasks.add({ ...taskPlan[i], assignee });
  }

  // Run each agent with streaming
  for (const agent of agents) {
    sendSSE(res, "status", { phase: "running_agent", agent: agent.name });

    for await (const { node, state } of agent.stream(goal)) {
      sendSSE(res, "step", {
        node,
        agent: agent.name,
        details: getStepDetails(node, state),
      });
    }

    // Report memory
    const episodes = agent.memory.episodic.all();
    if (episodes.length > 0) {
      sendSSE(res, "memory", {
        agent: agent.name,
        episodes: episodes.map((e) => ({ action: e.action, outcome: e.outcome, reward: e.reward })),
      });
    }
  }

  sendSSE(res, "status", { phase: "complete", taskStats: factory.tasks.stats(), messages: factory.bus.history(undefined, 50).length });
  sendSSE(res, "done", {});
  res.end();
}

function getStepDetails(node: string, state: { perception?: string; reasoning?: string; reflection?: string; output?: string; currentTask?: unknown; actionResult?: unknown }) {
  switch (node) {
    case "perceive": return { perception: state.perception?.slice(0, 300) };
    case "reason": return { reasoning: state.reasoning?.slice(0, 300) };
    case "plan": return { planned: true };
    case "act": return { task: (state.currentTask as Record<string, unknown>)?.description, result: state.actionResult };
    case "reflect": return { reflection: state.reflection?.slice(0, 300), output: state.output?.slice(0, 500) };
    case "escalate": return { escalated: true, output: state.output?.slice(0, 300) };
    default: return {};
  }
}

// ── Server ─────────────────────────────────────────────────────

const server = http.createServer(async (req, res) => {
  const parsed = url.parse(req.url ?? "/", true);
  const path = parsed.pathname;

  // CORS preflight
  if (req.method === "OPTIONS") {
    res.writeHead(204, { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Methods": "POST,GET,OPTIONS", "Access-Control-Allow-Headers": "Content-Type" });
    res.end();
    return;
  }

  try {
    if (path === "/" && req.method === "GET") {
      res.writeHead(200, { "Content-Type": "text/html" });
      res.end(html);
      return;
    }

    if (path === "/api/health") {
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ ok: true }));
      return;
    }

    if (path === "/api/demos") {
      res.writeHead(200, { "Content-Type": "application/json" });
      // Return demo metadata (no client needed)
      res.end(JSON.stringify([
        { id: "math", name: "Math Solver", description: "Single agent solves a math word problem", mode: "single" },
        { id: "research", name: "Research Team", description: "3 agents: Researcher → Writer → Reviewer", mode: "multi" },
        { id: "custom", name: "Custom Goal", description: "Type your own goal", mode: "single" },
      ]));
      return;
    }

    if (path === "/api/run" && req.method === "POST") {
      const body = await parseBody(req);
      const apiKey = (body.apiKey as string) || process.env.ANTHROPIC_API_KEY;
      if (!apiKey) {
        res.writeHead(400, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: "API key required" }));
        return;
      }

      const client = new Anthropic({ apiKey });
      const demoId = body.demoId as string;
      const customGoal = body.goal as string;
      const demos = buildDemos(client);
      const demo = demos.find((d) => d.id === demoId) ?? demos[2];
      const goal = customGoal || demo.goal;

      if (!goal) {
        res.writeHead(400, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: "Goal is required" }));
        return;
      }

      res.writeHead(200, sseHeaders());

      if (demo.mode === "single") {
        await runSingleAgent(res, client, goal, demo.singleTools ?? [], demo.singlePersona ?? "You are a helpful assistant.");
      } else {
        await runMultiAgent(res, client, goal, demo);
      }
      return;
    }

    res.writeHead(404, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: "Not found" }));
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    if (!res.headersSent) {
      res.writeHead(500, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: msg }));
    } else {
      sendSSE(res, "error", { error: msg });
      res.end();
    }
  }
});

server.listen(PORT, () => {
  console.log(`\n  Agent Playground running at http://localhost:${PORT}\n`);
  if (process.env.ANTHROPIC_API_KEY) {
    console.log("  API key: loaded from environment");
  } else {
    console.log("  API key: enter in the browser UI");
  }
  console.log();
});
